- name: backup log
  command: mv {{ item.src }} {{ item.dest }}
  loop:
    - {
        src: /var/log/nginx/access.log,
        dest: "/var/log/nginx/access.log_{{ now(fmt='%H:%M:%S') }}"
      }
  notify:
    - restart nginx
  ignore_errors: yes

# Nginx の設定ファイルのコピー
- name: copy nginx configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  notify:
    - restart nginx
  loop:
    - { src: nginx.conf, dest: /etc/nginx/nginx.conf }
    - { src: isucon.conf, dest: /etc/nginx/sites-enabled/isucon.conf }

# Nginx の設定ファイルのチェック
- name: check nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  register: result
  changed_when: False

- name: check nginx configuration
  fail:
    msg: "nginx configuration is invalid"
  when: result.rc != 0
